### ISSUE TITLE
Separate wallpapers out of repo

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#1]
They're too heavy. We should fetch them live from a separate repo so they don't have to live in the git history and weigh things down.

**Comment by orthotypos** [comment]
This is good idea generally, but also fwiw compressing these images on [tinify](https://tinypng.com/) give significant savings:
![image](https://github.com/basecamp/omakub/assets/9505695/1231ef7e-2122-4ed6-974e-46744ff9deb1)

probably worth doing it regardless of the move to the new repo.

**Comment by dhh** [comment]
Those savings look suspiciously large. As-in quality taking a major hit to get there. But yes, otherwise I'm totally game to just reduce the size of the backgrounds.

**Comment by dhh** [comment]
Actually, I think we're fine just leaving these 7 wallpapers in the back for now. If we get more sophisticated later with multiple choices or rotation we can revisit.
