### ISSUE TITLE
No user confirmation for Optional apps, it install them anyways

### ISSUE THREAD

**Issue by przbadu** [basecamp/omakub#112]
Fresh installed Ubuntu 24.04, I run `wget -qO- https://omakub.org/install | bash` command and it never ask me for my confirmation to install optional apps like 1password7, dropbox, spotify and others listed in the Optional directory here: https://github.com/basecamp/omakub/tree/master/install/optional.

**Comment by przbadu** [comment]
### Here is the code:

https://github.com/basecamp/omakub/blob/master/install/select-optional-apps.sh

Looking at the code, does this means, `gum` is not suppose to ask for confirmation and auto-select `--selected "1password","Spotify","Zoom"` these apps for install?

**Comment by matsest** [comment]
@przbadu That command will install the version from the [stable branch](https://github.com/basecamp/omakub/tree/stable) which at this time does not contain those changes.

If you want to install the version from the master branch you will need to run the [install-dev script](https://github.com/basecamp/omakub-site/blob/master/install-dev).

**Comment by dhh** [comment]
Yes, the optional feature hasn't been merged to stable yet. Happening today!
