### ISSUE TITLE
Turn off lazyvim plugin updates overlay

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#115]
Love everything about lazyvim EXCEPT that every time it starts, we get this overlay telling us about plugin updates. It blocks a fair chunk of the editor. Pretty annoying. Let's config that away.

![image](https://github.com/basecamp/omakub/assets/2741/f3b6bf74-e5f9-4a46-ad1e-9a4338b31bdb)

**Comment by MislavPukljak** [comment]
Would you like to remove that notify window in general or just plugin update part?

**Comment by dhh** [comment]
That entire window. There should be nothing on startup. Except, maybe, if possible, showing failures.

**Comment by MislavPukljak** [comment]
Find a solution, should I put it as an option to disable plugin notification?
Or would you prefer to always be disabled?

**Comment by dhh** [comment]
Always disabled, but it'll be a file generated in .config/nvim, so the user is always able to turn back on, if they prefer.
