### ISSUE TITLE
choose in which app update theme

### ISSUE THREAD

**Issue by MislavPukljak** [basecamp/omakub#123]
Should we make confirmation for every app when want to change theme.
For example I would like to change theme in the gnome but not on nvim, so when we press to change theme, pop up question "do you want to update nvim theme?", "gnom theme?", "alacritty theme?", or that is just unnecessary complication?

**Comment by dhh** [comment]
Too complicated, I think. You can always tweak the theme after its been installed, but they're designed to work together.
