### ISSUE TITLE
Problem with Typora installation on master

### ISSUE THREAD

**Issue by majur** [basecamp/omakub#125]
Installation failed on fresh Ubuntu 24.04 when it is running from master. Here is last lines of log:

Setting up libgit2-1.7:amd64 (1.7.2+ds-1ubuntu3) ...
Setting up apache2-utils (2.4.58-1ubuntu8.1) ...
Setting up bat (0.24.0-1build1) ...
Setting up eza (0.18.2-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Repository: 'deb https://typora.io/linux ./'
Description:
Archive for codename: ./ components: 
More info: https://typora.io/linux
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_typora_io_linux-noble.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_typora_io_linux-noble.list
Warning: The unit file, source configuration file or drop-ins of apt-news.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of esm-cache.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hit:1 http://sk.archive.ubuntu.com/ubuntu noble InRelease                                                              
Hit:2 https://cli.github.com/packages stable InRelease                                                                 
Hit:3 https://updates.signal.org/desktop/apt xenial InRelease                                                          
Hit:4 http://sk.archive.ubuntu.com/ubuntu noble-updates InRelease                                                      
Hit:5 https://dl.google.com/linux/chrome/deb stable InRelease                                                          
Hit:6 http://sk.archive.ubuntu.com/ubuntu noble-backports InRelease                                                    
Hit:7 http://security.ubuntu.com/ubuntu noble-security InRelease                          
Hit:8 https://ppa.launchpadcontent.net/zhangsongcui3371/fastfetch/ubuntu noble InRelease  
Get:9 https://typora.io/linux ./ InRelease [793 B]                                        
Err:9 https://typora.io/linux ./ InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
Reading package lists... Done
W: GPG error: https://typora.io/linux ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
E: The repository 'https://typora.io/linux ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Warning: The unit file, source configuration file or drop-ins of apt-news.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of esm-cache.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hit:1 http://sk.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 https://cli.github.com/packages stable InRelease                                                                 
Hit:3 http://sk.archive.ubuntu.com/ubuntu noble-updates InRelease                                                      
Hit:4 https://updates.signal.org/desktop/apt xenial InRelease                                                          
Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease                                                       
Hit:6 https://dl.google.com/linux/chrome/deb stable InRelease                                                          
Hit:7 http://sk.archive.ubuntu.com/ubuntu noble-backports InRelease                                                    
Hit:8 https://ppa.launchpadcontent.net/zhangsongcui3371/fastfetch/ubuntu noble InRelease               
Get:9 https://typora.io/linux ./ InRelease [793 B]
Err:9 https://typora.io/linux ./ InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
Reading package lists... Done
W: GPG error: https://typora.io/linux ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
E: The repository 'https://typora.io/linux ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Additional info:**
I was running it in VirtualBox on Mac mini 2018. The same VM works for installation from stable.

**Comment by dhh** [comment]
I haven't been able to reproduce this problem. Anyone else?

**Comment by DR-DinoMight** [comment]
I had this issue on a new install on a Dell XPS 13. 

However after running the installation of [typora](https://typora.io/#linux)  manually, then re-running the install script it worked.
