### ISSUE TITLE
Prompt tooling: Oh My Posh

### ISSUE THREAD

**Issue by csfh** [basecamp/omakub#126]
I have a PR already to customize prompts but I figured it may be a lot of ground to cover for us to satisfy everyone in an easy way.

Just like mise is an all-in-one option for installing various language runtimes and compilers, Oh My Posh has the potential to do the same but for prompt. Of course with some beautiful, sane and curated defaults.

https://ohmyposh.dev

**Comment by dhh** [comment]
I like the idea of this. And having a curated set of default prompts to pick from too. I like mine super minimal, and leaning on zellij for path, but I think it's a great place for some personalization too. Please do explore.

**Comment by dimitrismistriotis** [comment]
If allowed to suggest an alternative, I really liked + using: <https://starship.rs> which looks to have similar targets with Oh My Posh, "*to work with any shell*".

**Comment by JxJxxJxJ** [comment]
Yeah I use starship and I think it could go very well with omakub. Specially if the themes get changed for it as well 
![image](https://github.com/basecamp/omakub/assets/103049321/71ccc92f-59db-44e6-8ae1-decb83662a08)

**Comment by florentdestremau** [comment]
did the same on my custom post-omakub template

    curl -sS https://starship.rs/install.sh | sh
    starship preset pure-preset -o ~/.config/starship.toml

**Comment by dimitrismistriotis** [comment]
> did the same on my custom post-omakub template
> 
> ```
> curl -sS https://starship.rs/install.sh | sh
> starship preset pure-preset -o ~/.config/starship.toml
> ```

This is the uninstall:

```shell
# Locate and delete the starship binary
sh -c 'rm "$(command -v 'starship')"'
```

Plus removal from shell configuration

Source: https://starship.rs/faq/

**Comment by dhh** [comment]
I explored Starship at length, but never did come up with a prompt that felt worth the space it took up when running under Zellij where the path is in the pane. If someone wants to propose some potential prompts that don't feel redundant like that, I'd be happy to consider, though.

**Comment by florentdestremau** [comment]
![image](https://github.com/basecamp/omakub/assets/2852204/f8c388c7-cfc5-4c61-9a82-1ab65db5e99a)
I don't like (force of habit probably) having to read the path in the pane, the pure implementation seems very ok to me!

**Comment by JxJxxJxJ** [comment]
Yeah, it's fully customizable. No need to see anything you don't like. Personally I think the most potential is in the theming aspect, specially in sync with the color scheme scripts

**Comment by csfh** [comment]
I'd support if anyone else wants to attempt integrating either omp or starship. The key integration point being changing along with the themes of omakub.

**Comment by dhh** [comment]
I like what starship is doing, but I don't see any default prompt that I'd prefer to have in Omakub. So I think we should just leave this as something that people can pursue themselves. We could add a pointer to the docs, though.
