### ISSUE TITLE
<Alt>1- <Alt>9 conflict

### ISSUE THREAD

**Issue by clneagu** [basecamp/omakub#144]
The default \<Alt\>number keybinding gets overridden ... it's usually used to change tabs in the Terminal and also in browsers.
<code>
org.gnome.Terminal.Legacy.Keybindings switch-to-tab-1 '\<Alt\>1'
</code>

Your values:
<code>
org.gnome.Terminal.Legacy.Keybindings switch-to-tab-1 '\<Alt\>1'
org.gnome.shell.keybindings switch-to-application-1 ['\<Alt\>1']
</code>

Suggested (also 8 workspaces is better in the long run but that might be just my preference):
<code>
gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 8
org.gnome.desktop.wm.keybindings switch-to-workspace-1 ['\<Super\>F1', '\<Super\>Home']
org.gnome.desktop.wm.keybindings switch-to-workspace-2 ['\<Super\>F2']
org.gnome.desktop.wm.keybindings switch-to-workspace-3 ['\<Super\>F3']
org.gnome.desktop.wm.keybindings switch-to-workspace-4 ['\<Super\>F4']
org.gnome.desktop.wm.keybindings switch-to-workspace-5 ['\<Super\>F5']
org.gnome.desktop.wm.keybindings switch-to-workspace-6 ['\<Super\>F6']
org.gnome.desktop.wm.keybindings switch-to-workspace-7 ['\<Super\>F7']
org.gnome.desktop.wm.keybindings switch-to-workspace-8 ['\<Super\>F8', '\<Super\>End']
</code>

\<Super\>F1 is showing some annoying useless help that needs to be disabled anyway.
Nobody seems to be using the \<Super\>F keys for something else.

**Comment by dhh** [comment]
Alacritty has no tabs and you can use ctrl+1/2/3 for tabs in chrome.
