### ISSUE TITLE
Can't ctrl+click links in Alacritty

### ISSUE THREAD

**Issue by florentdestremau** [basecamp/omakub#146]
I feel like this should be a default for terminal for newcomers. Couple of examples where it's useful:

- login from shell
- click on "localhost:8000" for local dev
- click on links to generate github tokens
- debug/docs links

Currently you have to select with mouse, `ctrl+shift+c` to copy and then paste in a new tab, very user-unfriendly :smile: 

To add on to this: can't paste with middle click either (very useful for tokens, links, codeblocks, etc.)

**Comment by movstox** [comment]
did you try 'shift+click'?

**Comment by florentdestremau** [comment]
oooh right this is nice !

As for the paste with middle click, is there a hack?

**Comment by morgoth** [comment]
@florentdestremau the "Shift + Middle Mouse Button" works for pasting

**Comment by florentdestremau** [comment]
duh, didn't think about trying. Thanks a lot !
