### ISSUE TITLE
How are we to handle arm64, since snapdragon is coming soon

### ISSUE THREAD

**Issue by iljo-dp** [basecamp/omakub#15]
I don't really have any strong input here, but I tought to perhaps leave this issue here to discuss it, and let DHH propose a solution we can all work on.

**Comment by iljo-dp** [comment]
First we should determine if the user running the script uses arm64 or amd64 we can do this the following way

```bash
if uname -m | grep -q "aarch64"; then
    echo "ARM64 architecture"
fi

if uname -m | grep -q "x86_64"; then
    echo "AMD64 (x86_64) architecture"
fi
```
I think the script should be 1 command for any architecture, and that we detect arm64 or amd64 and change our downloads accordingly. I think the first step is now finding which apps all are specifically amd64, so we should compile a list for them(for example, neovim)
And if we have a list and a way of detecting arm or amd the next step is to implement a way to change which to install

**Comment by drale2k** [comment]
I tried to install it inside a VM on my Mac. I guess a lack of ARM support is why most tools are missing. Would be nice to support this, especially for people on a Mac who want to try it out 😆

**Comment by iljo-dp** [comment]
@dhh do you want 2 files, one for arm64 and one for amd64, or an if statement to check if arm64 or amd64? 
I'd start you omakub script by doing the check I did above here, and then setting a variable like arm = true for example. And if we do if else we can just check if arm is true or not and then run the different file? You find this good or not

**Comment by iljo-dp** [comment]
if given a go, or a direction I'd like to implement this and try to get this working :D

**Comment by zdeneksvarc** [comment]
Omakub on arm64 for example does not support out of the box Zellij and Spotify.

**Comment by zdeneksvarc** [comment]
Hardcoded `x86`: https://github.com/search?q=repo%3Abasecamp%2Fomakub%20x86&type=code

**Comment by iljo-dp** [comment]
today/tomorrow I'il start with the arm64 additions

**Comment by iljo-dp** [comment]
by the end of today I'il submit my pr with the fixes for arm64
It's going along very nice

**Comment by iljo-dp** [comment]
should be ready now, there are some apps that don't have an arm port, currently I just didn't support this, since this is DHH's script I won't choose alternatives for him(like web apps), but I think i'm ready now, if someone wants to review the code I'd be very glad #29

**Comment by gobijan** [comment]
Just wanted to testdrive omakub in a Ubuntu ARM64 24.04 LTS and it's ofc not running through.
Temporary fix could be to disable all things that are not installable with ARM64?

**Comment by dhh** [comment]
Working on this in #29. Let's focus all the discussion there.

**Comment by rlimberger** [comment]
#29 was closed. Is there another issue that tracks ARM support? FWIW, I am interested in running Omakub on a M1 MBP

**Comment by dhh** [comment]
@rlimberger You have Asahi Linux installed on that M1? Because you can't just install Ubuntu on an M1.

**Comment by rlimberger** [comment]
Yes, Asahi. I think there are a lot of us interested in trying Omakub on our existing MBP's before we go Framework. Would be cool if we could get Omakub working on Asahi / ARM. 🙏
