### ISSUE TITLE
Remove optional packages from default installation command

### ISSUE THREAD

**Issue by Clay26** [basecamp/omakub#150]
Can we remove optional packages: Spotify, WhatsApp, 1Password, etc. from the default installation command? These can be already be installed later using the `omakub install` command. Including them by default adds unnecessary bloat for users who don't need them in their development environment.

This change could streamline the installation process and allow users to customize their setup more effectively.

Opening this issue for discussion on this topic.

**Comment by rmacklin** [comment]
It's not in the `stable` branch yet, but this change is already in `master`: https://github.com/basecamp/omakub/commit/1f478d26b8df0f592c859cc9eebfededc748272e which allows selecting / unselecting optional apps. WhatsApp is separate but it's just a [chrome shortcut](https://github.com/basecamp/omakub/blob/431cc8b84634b3af5c7c0db3c40f137f192a939e/applications/WhatsApp.sh#L6) which can be removed by deleting `>~/.local/share/applications/WhatsApp.desktop`

**Comment by Clay26** [comment]
Ah nice, thank you. Will close this issue.
