### ISSUE TITLE
Alacritty has no installation candidate

### ISSUE THREAD

**Issue by GRawhideMart** [basecamp/omakub#162]
Would be nice to have alternatives, in case something like this happens and the whole script blocks. Is there a workaround?

**Comment by csfh** [comment]
What exactly happened?

**Comment by GRawhideMart** [comment]
> What exactly happened?

That at some point the execution of the script stops because Alacritty has no installation candidate

**Comment by Llourn** [comment]
I had this same issue. Turns out I was trying to run Omakub on Ubuntu v22. Installing v24 fixed the issue and everything seems to have installed correctly.

**Comment by florentdestremau** [comment]
@vamsea2002 @GRawhideMart a detail of your os version + computer would help maybe narrow down the issue ?

**Comment by dhh** [comment]
Omakub is only for 24.04+. We're working on getting a hard block installed for that.
