### ISSUE TITLE
Alacritty terminal shows without a window title bar

### ISSUE THREAD

**Issue by shariqmus** [basecamp/omakub#165]
Thanks for the great software.

One issue I faced is that Alacritty terminal shows without a window title bar meaning we cant resize it

![image](https://github.com/basecamp/omakub/assets/26157749/e51798de-d8e1-4067-b4d2-8b51be91c44e)

**Comment by arni1981** [comment]
Use Tactile extension or the gnome shortcuts to move windows around with the keyboard. https://github.com/basecamp/omakub/blob/master/help/tactile.md & https://github.com/basecamp/omakub/blob/master/help/hotkeys.md

**Comment by csfh** [comment]
By design afaik. What Captain (@arni1981) said.

**Comment by MislavPukljak** [comment]
Also in ~/.config/alacritty/alacritty.toml you can change config do set default terminal dimension.

![Screenshot from 2024-06-25 22-03-40](https://github.com/basecamp/omakub/assets/99070354/cd4e4614-129a-41cf-9ab6-5984fd53b5ce)

**Comment by dhh** [comment]
Yes, this is by design.
