### ISSUE TITLE
How do we add aliases without breaking Omakub Update?

### ISSUE THREAD

**Issue by singlebeam** [basecamp/omakub#166]
After adding to '~/.local/share/omakub/defaults/bash/aliases' the Omakub > Update script returns 
  
    error: cannot pull with rebase: You have unstaged changes.
    error: Please commit or stash them.

I assume this is by design....so I guess my question is:  How do I define bash aliases without breaking the designed setup?

Thank you for your time.

**Comment by arni1981** [comment]
This is not Omakub specific, just how git works.

**Comment by csfh** [comment]
Unless you want to maintain a separate fork of Omakub for your personal experience, I don't recommend changing any of the files. Customizing aliases can be done by adding them to your own `$HOME/.bashrc`

**Comment by singlebeam** [comment]
Thank you very much for your help.
