### ISSUE TITLE
Add menu restrictions / installation options

### ISSUE THREAD

**Issue by Rovel** [basecamp/omakub#17]
Great project. loved the Omakasse theme.
In the installation bash script or as env vars injection have a way to skip stuff like a menu, you know I'm allergic to Whatsapp XD

------------OS-----------
[  ] Flame
[  ] ......
---------- Apps ---------
[  ] Whatsapp
[  ] .... 
--------- Shell ---------
[  ]....

**Comment by dhh** [comment]
I don't want any upfront configuration. But I'd like to add bin/omakub-uninstall that would make it easy to take things out after the fact. Feel free to investigate!
