### ISSUE TITLE
FZF and Zellij CTRL-T conflict

### ISSUE THREAD

**Issue by grapev1ne** [basecamp/omakub#170]
If you open terminal and type **bat** or **n** and then **CTRL+f** Zellij changes to TAB mode instead of **fzf** showing file list. see fig 1 and 2).

It works fine in normal Terminal session (without Zeillij) running (see fig 3).

![image](https://github.com/basecamp/omakub/assets/115344233/6ba5f865-6eec-44f3-874a-df9add926a72)

I know this is more of a Zellij issue but would be nice to have no conflict out of the box.

_BTW: I  tried changing   keybindings but they have no affect:_

![image](https://github.com/basecamp/omakub/assets/115344233/676c83af-b7b5-40e8-a8db-8d533c8fe564)

![image](https://github.com/basecamp/omakub/assets/115344233/c94e56cb-6cee-4d7d-bc17-37f12b4e2604)

**Comment by MislavPukljak** [comment]
It is ctrl+t if you enter TAB mode.
You can go around it with "locked" mode (ctrl+g), then you can use ctrl+t as well.

**Comment by grapev1ne** [comment]
Thanks. Using locked mode fixed the problem.
