### ISSUE TITLE
Alacritty Font Size Change???

### ISSUE THREAD

**Issue by marksmith-dev** [basecamp/omakub#172]
Okay so I am a dummy... But I have just installed Omakub and I cannot seem to change the font size within Alacritty.

Can you advise on this or make this easier to do within the Omakub command / add an FAQ where you explain this?

BTW I am extremely impressed with Omakub!!!

Cheers

**Comment by rmacklin** [comment]
Have you tried updating this value:
https://github.com/basecamp/omakub/blob/431cc8b84634b3af5c7c0db3c40f137f192a939e/configs/alacritty.toml#L4
in your `~/.config/alacritty/alacritty.toml`?

(I'm just responding to "I cannot seem to change the font size within Alacritty", not the suggestion to add it to the omakub command or FAQ, which I'll leave to maintainers)

**Comment by ChowWiWang** [comment]
You can also use `ctrl +` or `ctrl -` to adjust the size on the fly.

**Comment by dhh** [comment]
Added a new menu for changing font size in the Omakub command.
