### ISSUE TITLE
 N: missing signed-by in the sources.list(5) 

### ISSUE THREAD

**Issue by siwka** [basecamp/omakub#173]
Everything works in a new installation in VM.
It is possible that the Omakub installation does not override & perhaps has conflicts with already set up env.
_______________

ubuntu 24.04 N: missing signed-by in the sources.list(5) entry for 'http://lenovo.archive.canonical.com'

My laptop , when installing Omakub, does not respond after log in. It is blank. Last command I run few times was 'sudo apt update'.
I noticed 'http://lenovo.archive.canonical.com' was modified today.

Still looking for a solution. I have access to my laptop only via Virtual Console.

Issues so far:
Super + T does not work. No way to use the set up. Where to fix it?
There are no graphics in Alacritty, just squares. Letters have weird space or get into each other.

**Comment by siwka** [comment]
There is a new file in home directory signal-desktop-keyring.gpg

**Comment by dhh** [comment]
Yeah, we're only designed to deal with a fresh Ubuntu installation. Not something that has already been setup.

**Comment by siwka** [comment]
I really like it. It was fast to set up & use in VM.

Do you have OMAKUB documentation or we've to figure out weeks by ourselves? e.g. I do not have WhatsUp & no intention to install it.
