### ISSUE TITLE
Does Omakub require Ubuntu 24?

### ISSUE THREAD

**Issue by javajosh** [basecamp/omakub#174]
I just noticed on the website that "Ubuntu 24 is required. I installed over 22. It doesnt work entirely right. Suggest emphasizing this more clearly.

**Comment by florentdestremau** [comment]
the 2nd line of the website mentions it.

> OMAKUB
> An Omakase Developer Setup for Ubuntu 24.04 by DHH

But it might be useful to check with `lsb_release -r` and display a warning if it's not 24.04

**Comment by javajosh** [comment]
Thanks, yes I just saw that. I think it would be wise for the installer to check the distribution name and version and **_abort_** if the requirements are not met. 

I unwisely installed over Ubuntu 22 and my login shell is failing critically: commands like `ls` aren't working. "Oh My Zsh" and its configuration isn't working either. It looks like `zsh` was uninstalled, and my oh-my-zsh configs deleted. 

I'm not entirely sure what to do, not knowing Ubuntu very well. I'm not entirely sure what Omakub did, or how to undo it. I'm not sure if I can get out of this situation by upgrading Ubuntu 22 to 24 (which seems not to have any official docs (!) but there is an [unofficial guide](https://www.cyberciti.biz/faq/how-to-upgrade-from-ubuntu-22-04-lts-to-ubuntu-24-04-lts/). Another alternative is to back out of omakub entirely, but I don't see uninstall directions, and it's not clear if your install script is reversible. Advice on this point is appreciated.

Note that, with some exceptions (for example Alacritty is missing entirely), the desktop is working so I can get into home directory files to make edits with GUI tools. Additionally, it looks like omakub uninstalled `zsh` entirely so at first I was unable to run a subshell. I was able to reinstall `zsh` with `sudo apt install zsh` and get a subshell with working `ls`. So that's something, I guess.

**Comment by javajosh** [comment]
I was able to get out of trouble by upgrading Ubuntu 22 to 24 using [these instructions](https://www.cyberciti.biz/faq/how-to-upgrade-from-ubuntu-22-04-lts-to-ubuntu-24-04-lts/), and then reinstalling Omakub. Note that all Ubuntu 22 users will be able to upgrade more easily on August 15, or so I hear. But I needed a working machine now.

I'm still a bit puzzled as to why/how it appears that my shell was so badly broken, with cd and ls not working, etc. I took the time to read through the Omakub install scripts, and didn't see anything in them that could cause that problem. Perhaps it was something done by the install scripts of the dependencies. This is a good reason to add a version check to the primary install script, perhaps something like:

```
#!/bin/bash

# Function to compare version numbers
version_compare() {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

# Check if the system is Ubuntu
if [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    if [ "$DISTRIB_ID" != "Ubuntu" ]; then
        echo "This script is intended for Ubuntu systems only."
        exit 1
    fi
else
    echo "This script is intended for Ubuntu systems only."
    exit 1
fi

# Get Ubuntu version
ubuntu_version=$(lsb_release -rs)

# Minimum required version
min_version="24.04"

# Compare versions
version_compare $ubuntu_version $min_version
result=$?

if [ $result -eq 2 ]; then
    echo "Error: Ubuntu version $ubuntu_version is lower than the required version $min_version"
    exit 1
else
    echo "Success: Ubuntu version $ubuntu_version meets the minimum requirement of $min_version"
    exit 0
fi

```

**Comment by dhh** [comment]
There's a PR to institute a version check.
