### ISSUE TITLE
Broken install on fresh Ubuntu 24.04 running on Raspberry Pi 5

### ISSUE THREAD

**Issue by joelgrimberg** [basecamp/omakub#177]
when I try to install OmaKub on a fresh Ubuntu 24.04 on my Pi 5, I get the following error:

Command : wget -qO- https://omakub.org/install | bash
Output:

Installing git...
Cloning stable OMAKUB...
fatal: destination path '/home/joelgrimberg/.local/share/omakub' already exists and is not an empty directory.
________                  __        ___.
\_____  \   _____ _____  |  | ____ _\_ |__
 /   |   \ /     \__   \ |  |/ /  |  \ __ \
/    |    \  Y Y  \/ __ \|    <|  |  / \_\ \
\_______  /__|_|  (____  /__|_ \____/|___  /
        \/      \/     \/     \/         \/
Hit:1 http://ports.ubuntu.com/ubuntu-ports noble InRelease
Hit:2 https://downloads.1password.com/linux/debian/arm64 stable InRelease      
Hit:3 http://ports.ubuntu.com/ubuntu-ports noble-updates InRelease             
Hit:4 http://ports.ubuntu.com/ubuntu-ports noble-backports InRelease           
Hit:5 http://ports.ubuntu.com/ubuntu-ports noble-security InRelease            
Reading package lists... Done                                                  
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (8.5.0-2ubuntu10.1).
git is already the newest version (1:2.43.0-1ubuntu7.1).
unzip is already the newest version (6.0-28ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
--2024-06-28 21:08:19--  https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
Resolving downloads.1password.com (downloads.1password.com)... 18.239.83.105, 18.239.83.126, 18.239.83.56, ...
Connecting to downloads.1password.com (downloads.1password.com)|18.239.83.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 134279118 (128M) [application/x-debian-package]
Saving to: ‘1password-latest.deb.5’

1password-latest.deb.5                                                                        100%[=================================================================================================================================================================================================================================================>] 128.06M  97.8MB/s    in 1.3s    

2024-06-28 21:08:21 (97.8 MB/s) - ‘1password-latest.deb.5’ saved [134279118/134279118]

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting '1password:amd64' instead of './1password-latest.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 1password:amd64 : Depends: libasound2:amd64 but it is not installable
                   Depends: libatk-bridge2.0-0:amd64 but it is not installable
                   Depends: libatk1.0-0:amd64 but it is not installable
                   Depends: libc6:amd64 (>= 2.27) but it is not installable
                   Depends: libcurl4:amd64 but it is not installable
                   Depends: libdrm2:amd64 but it is not installable
                   Depends: libgbm1:amd64 but it is not installable
                   Depends: libgtk-3-0:amd64 but it is not installable
                   Depends: libnotify4:amd64 but it is not installable
                   Depends: libnss3:amd64 but it is not installable
                   Depends: libxcb-shape0:amd64 but it is not installable
                   Depends: libxcb-xfixes0:amd64 but it is not installable
                   Depends: libxshmfence1:amd64 but it is not installable
                   Depends: libudev1:amd64 but it is not installable
                   Recommends: libappindicator3-1:amd64 but it is not installable
                   Recommends: libappindicator1:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by derekslenk** [comment]
This guide kind of assumes you have Intel/AMD. Seems to focus on devs going from Windows -> Linux. 

You would at the minimum change the .debs that are downloaded since they are compiled for amd64

**Comment by rwiankowski** [comment]
I just tried it on an M-series Mac in a VM and got the same error. Like derekslek said, the scripts assume you're on amd64 architecture.

If you want to try to fix it, you can follow the steps described here: https://askubuntu.com/questions/430705/how-to-use-apt-get-to-download-multi-arch-library

But then you'd probably need to update all the apt install commands in the install scripts located in ~/.local/share/omakub/install to use the format `apt install -y <package>:<architecture>`.

The whole hassle kind of defeats the whole idea of a single commandd deployment. You might as well go install Arch, add all the packages with pacman and only copy over the dotfiles provided by Omakub ;)

**Comment by Fopdoodle2** [comment]
Thank you for posting this and answering. I thought I'd use Omakub to dip my toe in Linux, having only ever used Windows and Mac. I'm running it as a virtual machine using parallels on my Macbook Air M2. and had the same errors.

More investigations as a Linux noob before I start.

**Comment by joelgrimberg** [comment]
My suggestion would be to check for the architecture on install and abort before cloning the git repo.
The site does not state a requirement that OmaKube only runs on Intel/AMD.

**Comment by rwiankowski** [comment]
I attempted to fix the installation scripts by:
- replacing apt install with snap install where possible
- changing the download links to get arm64 or aarch64 binaries where possible
- removing a few apps that are not supported on arm64 linux

The app install process, including Zellij, worked OK. But the bit that comes after it bricked my VM 🙈 I will keep trying to get it to work.

**Comment by dhh** [comment]
We're working on this problem in #29. Please add notes there.
