### ISSUE TITLE
omakub dosen't work on ubuntu on UTM on M3 iMac, should remove installaon of applications not having Arm versions?

### ISSUE THREAD

**Issue by richvote** [basecamp/omakub#179]
I had the following error message when I use omakub on ubuntu on UTM of m3 imac. these errors might be caused by the lack of some Arm versions of applications.

Note, selecting '1password:amd64' instead of './1password-latest.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 1password:amd64 : Depends: libasound2:amd64 but it is not installable
                   Depends: libatk-bridge2.0-0:amd64 but it is not installable
                   Depends: libatk1.0-0:amd64 but it is not installable
                   Depends: libc6:amd64 (>= 2.27) but it is not installable
                   Depends: libcurl4:amd64 but it is not installable
                   Depends: libdrm2:amd64 but it is not installable
                   Depends: libgbm1:amd64 but it is not installable
                   Depends: libgtk-3-0:amd64 but it is not installable
                   Depends: libnotify4:amd64 but it is not installable
                   Depends: libnss3:amd64 but it is not installable
                   Depends: libxcb-shape0:amd64 but it is not installable
                   Depends: libxcb-xfixes0:amd64 but it is not installable
                   Depends: libxshmfence1:amd64 but it is not installable
                   Depends: libudev1:amd64 but it is not installable
                   Recommends: libappindicator3-1:amd64 but it is not installable
                   Recommends: libappindicator1:amd64 but it is not installable

**Comment by dhh** [comment]
We're working on this in #29.
