### ISSUE TITLE
Hotkey (Super + T) for tiling suddently stopped working & Top left numbers of desktop views are missing.

### ISSUE THREAD

**Issue by danrayfr** [basecamp/omakub#180]
Hotkey (Super + T) for tiling suddenly stopped working and the Top left numbers of desktop views are missing. Opening an issue here in case someone has also encountered it. Not entirely sure how to fix the issue.

I am attaching the image here for reference on the top left corner for desktop navigation numbers.

![Screenshot from 2024-07-02 01-17-20](https://github.com/basecamp/omakub/assets/64381243/524d62e7-529a-48f1-a602-76fde4969677)

**Comment by dhh** [comment]
Looks like your Gnome extensions are not being loaded. Try launching "Gnome Extensions" through Ulauncher (Super + space) and see what it says.

**Comment by MislavPukljak** [comment]
Have the similar problem, top bar just randomly disappear, then I need to go to Gnome Extensions, disable Tactile, enable it again, and than everything is back..

![Screenshot from 2024-07-04 12-17-19](https://github.com/basecamp/omakub/assets/99070354/d0b9ca60-90fe-4e72-8ca6-9f2bf4c38fe7)

**Comment by ad798** [comment]
I have updated Omakub and find the same problem. I did what @MislavPukljak  suggested and is working now:

>  disable Tactile, enable it again

**Comment by ad798** [comment]
I was able to reproduce the error with Pano activated:

1. Activate Pano in Gnome Extensions
2. Copy a text
3. Paste the text
4. Result: The upper bar disappears

After deactivating Pano and trying to copy & paste it works fine.

**Comment by Giorgio-Zarantonello** [comment]
Just got the same error trying different combinations for the tilling used by Super + T

for @danrayfr : in the Ulauncher (super+space) , type "Extensions" , then enable "Use Extensions" 

for @dhh , i can reproduce the error using the "q+w+e" combination after using the Super + T command , that leads to a crash forcing me to log out, after that the gnome extensions are not reloaded in some cases ( i need to crash it a couple of times to reproduce this behaviour ) 

Omakub is awesome , looking forward to what this can become in the future with further optimizations :100:

**Comment by dhh** [comment]
I think we're going to have to report these bugs upstream to the respective projects. So please do pursue that!

Pano support for Gnome 46 is good enough on master to work well. So that's what we're pulling from. When they release a version that's completely done, we'll switch to that.
