### ISSUE TITLE
Omakub 1.1.0 Theme Change Error

### ISSUE THREAD

**Issue by mattgrieser** [basecamp/omakub#184]
`cp: cannot create regular file '/home/matt/.config/zellij/themes/everforest.kdl': No such file o
r directory`

**Comment by mattgrieser** [comment]
```
 cd ~/.config/zellij/
 lt
drwxrwxr-x  - matt  3 Jul 15:18  .
.rw-rw-r-- 44 matt  3 Jul 15:18 ├──  config.kdl
lrwxrwxrwx  - matt 13 Jun 21:46 └──  themes -> /home/matt/.local/share/omakub/themes/zellij
```

**Comment by dhh** [comment]
Did you run the migration script? Needed to convert the zellij theme setup.

**Comment by mattgrieser** [comment]
That script is not in my omakub-sub directory. Am I looking in the wrong place?

**Comment by mattgrieser** [comment]
I got it! I think it wasn't clear that the `source` part was a command here:
>Update, then running source $OMAKUB_PATH/migrations/1718359027.sh (going forward these migrations will run automatically when running Update).
Some additional formatting might make that clearer. Thank you all again for the efforts!
