### ISSUE TITLE
Interest for Nix Home Manager support?

### ISSUE THREAD

**Issue by jcpsimmons** [basecamp/omakub#191]
I have to say that the setup as-is works beautifully on Ubuntu 24.04 but

- shell scripts can be flaky
- it's only guaranteed working on one version of one distro of one operating system

I have been working on migrating my entire setup to use Nix's [Home Manager](https://nix-community.github.io/home-manager/) and found it _Just Works_ ™️ with some slight distinction necessary between linux/mac packages and services. Is there an interest or existing effort to migrate this to Nix?

**Comment by jcpsimmons** [comment]
My HM config for reference: https://github.com/jcpsimmons/home-manager/blob/master/flake.nix

**Comment by dhh** [comment]
No interest in that, no. Happy to see Omakub inspire a project that works through that though. So feel free to pursue that. But happy with shell scripts for Omakub.
