### ISSUE TITLE
Omakub Update to 1.1 not working?

### ISSUE THREAD

**Issue by pgruener** [basecamp/omakub#192]
Hi,
I installed omakub nearly 2 weeks ago on a fresh installed ubuntu 24 version.
A few days ago I noticed, there is an update (by X)
I've run the updater from the omakub TUI

I think I've made a mistake? When I launched it I wasn't in the home directory. The update call took just around 30 seconds.

However the updated omakube tui "thinks" it is updated (further update tells "you're up to date") but all the new features aren't there (for example Standalone Omakub app in SUPER+SPACE, Pano or Undecorate)

Is there something to check and/or force the update?

**Comment by MislavPukljak** [comment]
Try  to run the migration script manually, then you should have all new features.

**Comment by pgruener** [comment]
how? I 1st tried to cd into `.local/share/omakub/migrations/` and run `sh 1718359027.sh`

The result is 
```
1718359027.sh: 24: source: not found                                                                       │
│1718359027.sh: 30: source: not found                                                                       │
│1718359027.sh: 36: source: not found                                                                       │
│1718359027.sh: 39: source: not found                                                                       │
│1718359027.sh: 40: source: not found                                                                       │
│1718359027.sh: 41: source: not found                                                                       │
│1718359027.sh: 42: source: not found                                                                       │
│1718359027.sh: 43: source: not found                                                                       │
│1718359027.sh: 44: source: not found                                                                       │
│1718359027.sh: 47: source: not found                                                                       │
│1718359027.sh: 48: source: not found                                                                       │
│1718359027.sh: 49: source: not found                                                                       │
│1718359027.sh: 50: source: not found                                                                       │
│1718359027.sh: 53: source: not found                                                                       │
│1718359027.sh: 54: source: not found                                                                       │
│1718359027.sh: 55: source: not found                                                                       │
│1718359027.sh: 58: source: not found                                                                       │
│1718359027.sh: 61: source: not found
```

The same happens when I call it from the home directory via `sh .local/share/omakub/migrations/1718359027.sh` from home directory.

**Comment by rmacklin** [comment]
Try running it with `bash`, not `sh`. (Omakub scripts assume `bash`, though they don't have shebang comments, which [I think would be valuable](https://github.com/basecamp/omakub/pull/101#issuecomment-2167797663).)

**Comment by pgruener** [comment]
Ok great. From the home directory I called `bash  .local/share/omakub/migrations/1718359027.sh` which did much more actions (with less errors) than before. (including restart)

But still Pano seems to not be active. Reading omakub docs, SHIFT+SUPER+V should be used to call it, but it doesn't bring any action. 

Can I check somewhere if Pano was (correctly) installed and where the keybinding should have been setup?

**Comment by MislavPukljak** [comment]
You need to enable it in the "Extension Manager".

There is possibility that you'll have some problem with top bar disappear randomly, it is not for sure that will happen, but if it does, it is because Pano, just disable it and everything will be ok.

**Comment by MislavPukljak** [comment]
You can read a lot of this things in official manual.

https://manual.omakub.org/

**Comment by pgruener** [comment]
Ah, I didn't notice, that I dedicatedly need to activate it thanks!

**Comment by pgruener** [comment]
> You need to enable it in the "Extension Manager".
> 
> There is possibility that you'll have some problem with top bar disappear randomly, it is not for sure that will happen, but if it does, it is because Pano, just disable it and everything will be ok.

@MislavPukljak 
fyi: what you described happened. I stopped this, by changing the configuration to prevent Pano from being displayed in the taskbar (so it is active by keyboard bindings, but not visible in the taskbar). I needed to re-login, but from this time on, the top bar doesn't disappear anymore.

Maybe that's interesting for you ..
