### ISSUE TITLE
Expose colorscheme shell variable

### ISSUE THREAD

**Issue by JxJxxJxJ** [basecamp/omakub#195]
I used to have other apps' (lunarvim) configuration files change according omakub's changes through the `theme.sh` script. 

Now after trying to update I noticed many of these files changed and I saw how unpractical my approach was.

I think it'd be useful if omakub exposed a colorscheme variable so I could make my own scripts while not changing omakub's original files, making the update process more seamless.

**Comment by dhh** [comment]
Yeah, I've been thinking of having a ~/.config/omakub/settings.json or similar that would retain state, like current theme. Feel free to investigate and open a PR if you arrive at something pleasant!
