### ISSUE TITLE
top bar missing after resuming in VMware Workstation Pro

### ISSUE THREAD

**Issue by tge96** [basecamp/omakub#205]
navigation still works, rebooting now...

**Comment by tge96** [comment]
not 100% certain that this hidden top bar issue has anything to do with resuming the VM.  I tested a bit more and can't reproduce this simply by pausing the VM.

**Comment by ofrades** [comment]
I use regular Ubuntu and I can confirm
![image](https://github.com/basecamp/omakub/assets/31070771/fd29ce11-d802-4883-9bb3-65a51609925c)

**Comment by tge96** [comment]
see above workaround suggestion
