### ISSUE TITLE
WhatsApp Icon / Installing PWA

### ISSUE THREAD

**Issue by thomas992** [basecamp/omakub#208]
Clicking the WhatsApp icon from the super menu makes the app appear as a Google Chrome window. I removed that pin and replaced it with the PWA installed from Chrome. This is a benefit in that we can click the original icon to return to our WhatsApp. This is the only mention I found of installing PWAs from terminal.

[Microsoft Forum](https://techcommunity.microsoft.com/t5/discussions/is-it-possible-to-install-a-pwa-from-the-command-line/m-p/2740596)

--force-app-mode has no effect in my testing
google-chrome --app=http://www.duolingo.com does not install the app but opens it in App context

**Comment by dhh** [comment]
This should have been sorted with https://github.com/basecamp/omakub/pull/219
