### ISSUE TITLE
Consider adding Zed 

### ISSUE THREAD

**Issue by atohovitis** [basecamp/omakub#226]
Zed is now available on Linux. A beautiful new editor built for blazing performance and font rendering quality. 

https://zed.dev/blog/zed-on-linux

**Comment by rmacklin** [comment]
See https://github.com/basecamp/omakub/commit/66182b859df26fca06338d604bcbcd10728c11da

**Comment by florentdestremau** [comment]
There are missing themes for zed to be in sync with theme switching, tho, if you want to contribute 😉

**Comment by dhh** [comment]
Yes, would be great to get Zed themes synced up, if that's possible. But Zed is indeed part of the optional packages now.
