### ISSUE TITLE
Dock Docs

### ISSUE THREAD

**Issue by mrchantey** [basecamp/omakub#228]
Is there a place I can find out more about configuring the dock view, keybindings etc?

For my desktop pc the super key works fine with window tiling etc but of the two keyboards I have tested, 'Press super to reveal dock' only works on the left button of one of them. Knowing a bit more about how this is configured I might be able to investigate further.

**Comment by dhh** [comment]
There's no built-in feature in Ubuntu for remapping the super key to multiple keys. Your keyboard might support remapping using something like the VIA software, but that's it. You can, however, change keybindings under Settings >  Keyboard > System.

**Comment by mrchantey** [comment]
I can't find the 'Super opens dock' keybinding in `Settings > Keyboard > System`, am I missing something?
