### ISSUE TITLE
why there is nothing work after run this script ?

### ISSUE THREAD

**Issue by EsamLasheen** [basecamp/omakub#230]
![2024-07-25 14_30_57-Ubuntu-omakub - VMware Workstation](https://github.com/user-attachments/assets/b8ca0cfd-7748-469a-857b-0defd6944172)

**Comment by IbrahimTanyalcin** [comment]
This probably because of your architecture is not x64, try running `dkpg --print-architecture` or lscpu to check it. I have done [this PR](https://github.com/basecamp/omakub/pull/227), try cloning that repo and run the install script again. A few apps can fail, you will find `omakub_report.log` in the root after installation completes.

**Comment by linuxnoob21** [comment]
I'm also experiencing the same issue and my architecture is x64

**Comment by nestorjgomez** [comment]
Hi @IbrahimTanyalcin! Greetings to you from Argentina 🇦🇷
I have the same issue @EsamLasheen mentioned a few hours ago... My architecture is x86_64 Does it work with it?
I've had installed 3 times Ubuntu 24.04 LTS to run this script.
The first time I've executed I've had receive this warning: The unit file, source configuration file or drops-on of apt-news.service changed on disk. Run 'systemctl daemon-reload' to reload units. It happened twice.
This is the terminal screenshot ![IMG_20240725_104509_991.jpg](https://github.com/user-attachments/assets/a5a7d12c-4591-47a5-bf5b-5f1b182b41c3)

Could you help me to solve it? I don't do an sudo apt update to avoid not to have an Ubuntu "fresh install". Thank you!

**Comment by cyommer** [comment]
There's an issue with the `gum` installation as part  of the install script.

There's a script referenced in the installer (`app-gum.sh`) that looks like this:

```bash
# Gum is used for the Omakub commands for tailoring Omakub after the initial install
cd /tmp
GUM_VERSION="0.14.1" # Use known good version
wget -qO gum.deb "https://github.com/charmbracelet/gum/releases/latest/download/gum_${GUM_VERSION}_amd64.deb"
sudo apt-get install -y ./gum.deb
rm gum.deb
cd -
```
It's setting the `GUM_VERSION` to `0.14.1`, but the `wget` link points to `latest`.  Which will probably always break when new versions are released.  The fix would be to change this line:

```
wget -qO gum.deb "https://github.com/charmbracelet/gum/releases/latest/download/gum_${GUM_VERSION}_amd64.deb"
```

to this:

```
wget -qO gum.deb "https://github.com/charmbracelet/gum/releases/download/v{GUM_VERSION}/gum_${GUM_VERSION}_amd64.deb"
```

I'll see about created a PR here in a few minutes after I finish testing it just to be sure.

**Comment by nestorjgomez** [comment]
@cyommer Hi! I installed "gum"  using snap but a few minutes later I've found the same script about "gum" with the version is required to the script to work out... I'll wait your response. Thanks for your comment!

**Comment by cyommer** [comment]
@nestorjgomez :wave: 

As a quick workaround, you can maybe take one of two paths.

1. If you've already installed gum, you should be able to edit `~/.local/share/omakub/install.sh` and comment out this line:
```bash
source ~/.local/share/omakub/install/terminal/required/app-gum.sh >/dev/null
```
and then re-run the install from `~/.local/share/omakub/install.sh`.

or...

2. You could update `~/.local/share/omakub/install/terminal/required/app-gum.sh` with the changes mentioned in my previous comment.

Either way _should_ work.

**Comment by IbrahimTanyalcin** [comment]
@nestorjgomez it seems to be similar to this although not exactly the same, https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/2055239, they report it to be harmless, This should work:

```
wget -qO gum.deb "https://github.com/charmbracelet/gum/releases/latest/download/gum_${GUM_VERSION}_${ARCH}.deb"
sudo apt-get install -y ./gum.deb
rm gum.deb
```

you can replace GUM_VERSION with "latest" as @cyommer suggessted and ARCH should be `amd64` for x86_x64 and `arm64` for aarch64

**Comment by EsamLasheen** [comment]
@nestorjgomez 
does it work with you ?

**Comment by dhh** [comment]
Fixed the immediate issue in https://github.com/basecamp/omakub/commit/fcb3e9c40b4c36ee19c45543dfb5257239b72e42. But we need to fix that installer. It's using the latest path but with a specific version. And that breaks whenever there's a release of gum.

**Comment by nestorjgomez** [comment]
Thanks to all of you!! 
@dhh Do you recommend me to delete this previous version clone omakub again to test that it works? Greetings to you from Argentina!!

**Comment by dhh** [comment]
No, it'll automatically pull down the latest version when you run the installer again. So you can just paste and run.

**Comment by dhh** [comment]
Going to start a new ticket for the upgrade needed.

**Comment by dhh** [comment]
See https://github.com/basecamp/omakub/issues/231

**Comment by nestorjgomez** [comment]
I have followed the @cyommer e @IbrahimTanyalcin suggestions:
1. I manually downloaded the latest version of gum from the repository https://github.com/charmbracelet/gum/releases/tag/v0.14.3
2. Install it conf sudo dpkg -i ./gum_0.14.3_amd64.deb (as I show in the screenshot)
3. I modified and saved app-gum.sh like this:
GUM_VERSION="0.14.3"
# Use known good version
wget -qO gum.deb "https://github.com/charmbracelet/gum/releases/download/v{GUM_VERSION}/gum_${GUM_VERSION}_amd64.deb"
3. I modified install.sh and commented out the line:
  echo "Get ready to make a few choices..."
# source ~/.local/share/omakub/install/terminal/required/app-gum.sh >/dev/null
  source ~/.local/share/omakub/first_run_choices.sh
And it works (what you see in the screenshot is how I currently have it)
![Captura desde 2024-07-25 16-04-37](https://github.com/user-attachments/assets/d185243d-2115-482f-adbd-0c789dddcdb3)

**Comment by nestorjgomez** [comment]
It worked for me @dhh @cyommer @IbrahimTanyalcin @EsamLasheen @linuxnoob21!! Some warnings came up, but the installation was never stopped abruptly...
![Captura desde 2024-07-25 17-26-26](https://github.com/user-attachments/assets/530f2fe5-1ce2-4c5a-a276-777ad74f7393)
