### ISSUE TITLE
Fix Gum installer to use a path that's version agnostic

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#231]
The current Gum installer is using a download path that's bound to the latest version but also a specific version. So that breaks when Gum does a new release. I fixed the immediate issue in https://github.com/basecamp/omakub/commit/fcb3e9c40b4c36ee19c45543dfb5257239b72e42, but we need to fix the installer such that it uses a fully known good path.

**Comment by cyommer** [comment]
I created a PR for this, but it may be moot now.  Feel free to close if appropriate.  My change was very small.

#232
