### ISSUE TITLE
Flameshot not closing when Esc button pressed

### ISSUE THREAD

**Issue by h4r0n1** [basecamp/omakub#236]
Flameshot doesn't close when I press `Esc` button. I'm forced take screenshot and then copy or save it.

**Comment by melopilosyan** [comment]
Happens to me too every now and then. No need to take a screenshot though. Just select a region and click on the X button.

![2024-07-30_04-09](https://github.com/user-attachments/assets/3fa3019b-e580-4ace-b3c9-5ef7f9054bb2)

Or press `Ctrl+Q`.

A system upgrade could potentially resolve the issue.

```bash
sudo apt update && sudo apt upgrade -y
```
