### ISSUE TITLE
Missing chars on fonts

### ISSUE THREAD

**Issue by florentdestremau** [basecamp/omakub#249]
On linkedin, the latest (debatable) trend is to ~shit~post with fake latin chars in _italic_ or **bold**, and certain characters are missing, presumably from my local font ? It's typically the French accented letters éèê. I wonder if I'm alone on this and if it has something to do with the superfonts used in Omakub ?

![image](https://github.com/user-attachments/assets/96bb8f45-26d6-4732-8a23-238570f812fc)

![image](https://github.com/user-attachments/assets/5bcbbbcc-ed0a-4c35-a5c7-0b5be4a41751)

**Comment by Kasui92** [comment]
I'll try to open the articles with a freshly Omakub installation and I didn't have any missing chars.
Besides, Omakub installed fonts are used only for terminal and vscode.

Maybe it's something with your browser (theme, font or extension).

**Comment by florentdestremau** [comment]
same thing with different chrome session, but on Firefox it's not the case. Indeed Chrome seems to be the culprit

**Comment by liyuliang** [comment]
Font is missed in my ternimal , OS is ubuntu 24.04 LTS and there isn't any wrong message during the installation, how can i fixed it?

**Comment by Kasui92** [comment]
> Font is missed in my ternimal , OS is ubuntu 24.04 LTS and there isn't any wrong message during the installation, how can i fixed it?

@liyuliang  What do you mean by "missed"? 

In any case, you can check which font is in use for Gnome Terminal via Gnome Tweaks (Fonts > Monospace Text) and for Alacritty at the path `~/.config/alacritty/font.toml` .

**Comment by brablc** [comment]
I just created https://github.com/basecamp/omakub/pull/307, which fixes problems with fonts on fresh Ubuntu.
