### ISSUE TITLE
GPG Error - public key is not available 

### ISSUE THREAD

**Issue by RobertLikesCoding** [basecamp/omakub#250]
I can't seem to get past this error. I tried manually installing mise successfully but I still get this error when trying to run the omakub installation command.

![image](https://github.com/user-attachments/assets/2b623b37-d02c-4fc3-bac6-deca3f928183)
`W: GPG error: https://mise.jdx.dev/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B81C9D17413A06D
E: The repository 'https://mise.jdx.dev/deb stable InRelease' is not signed.
`

Does anyone know what to do? I installed Omakub without any issues on my testing laptop. Both HP Laptops, both times I freshly installed Ubuntu 24.04

I also tried this script from the mise.sh file (https://github.com/basecamp/omakub/blob/b08967ca2cb210c3b5af70f0c0f18ec945d8d390/install/terminal/mise.sh)

`sudo apt update -y && sudo apt install -y gpg sudo wget curl
sudo install -dm 755 /etc/apt/keyrings
wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1>/dev/null
echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
sudo apt update
sudo apt install -y mise`

**Comment by Kasui92** [comment]
I found this [issue](https://github.com/jdx/mise/issues/1910) in the `mise` repo. You can install the missing public key by using the existing script there.

**Comment by RobertLikesCoding** [comment]
Thanks a lot, that looks promising! Unfortunately I had to go ahead and install all my apps again so I could word. That means now I don't have a "fresh" installation of ubuntu, which is probably going to cause more trouble.
I'll have to verify this some other time, when I have reset ubuntu again.

**Comment by skyscooby** [comment]
It looks like this can be closed as the installer was fixed up to correctly install the product with this commit:

https://github.com/basecamp/omakub/commit/78a752bed2f8bae8e0bb4e3bb693a98f321a7fa0
