### ISSUE TITLE
you have wasted my whole morning.

### ISSUE THREAD

**Issue by rubenGit** [basecamp/omakub#26]
I'm not sure if you have a command to delete this configuration.

I'm going to have to fomate the fucking computer.

**Comment by rubenGit** [comment]
![Uploading Captura desde 2024-06-07 10-22-46.png…]()

**Comment by iljo-dp** [comment]
There is no current way to uninstall everything done by omakub, however if you want feel free to add a pull request adding that feature.
Omakub is not responsible for damage done to the computer, and shouldn't be blamed for you not reading what the script does. The script itself works great, but does overwrite configs and downloads stuff

**Comment by dhh** [comment]
The obstacle is the way. Embrace the journey. This is a setup script for a fresh ubuntu. If you apply it to anything but, you're on your own.
