### ISSUE TITLE
[ Help Required ] The system is unusable on MacBook Pro M1 16GB

### ISSUE THREAD

**Issue by therohitdas** [basecamp/omakub#260]
When using #259 on Macbook M1 Pro 16GB, the system is not very usable. 

Ulauncher exits when typing and refuses to open again; Alacrity starts an invisible window. Neovim does not open in the in-built terminal.

How do I debug? Is it even worth debugging given the 16GB RAM limit?

I want to make this available and usable on MacBooks so that MacBook people can try it and get hooked 😂

**Comment by nicodeory-homa** [comment]
I've also been running into issues on an M2 with both of the PRs, while running Ubuntu 24.04 Desktop inside VMWare Fusion. Docker daemon fails, Neovim closes instantly

**Comment by olli757** [comment]
It was confirmed in other PR's that it doesn't work on the ARM based Ubuntu. Would also love to give this a try on my Macbook Pro M1 though VM Ware Fusion Pro

**Comment by dhh** [comment]
Omakub is not yet ARM compatible. Lots of packages are missing etc. This is to be expected at this stage. But as Snapdragon ARM laptops get full Linux compatibility, I'm sure we'll be able to sort this out eventually.

**Comment by DoppioJP** [comment]
Here is my attempt to bring Omakub for the rest of us https://github.com/DoppioJP/omakub4all/tree/macos

I have used your work @therohitdas resulted in https://github.com/DoppioJP/omakub-arm, which I hope to rebase to the newest Omakub. Nevertheless I have been using https://github.com/DoppioJP/omakub-arm for 5 months on M1 under VirtualBox and it works well. VirtualBox crashes though ;-)
