### ISSUE TITLE
Problem when trying to confirm that I want to "Add Microsoft apt reposity to Visual Studio Code"

### ISSUE THREAD

**Issue by rysllvn** [basecamp/omakub#262]
![Screenshot 2024-09-06 172252](https://github.com/user-attachments/assets/c64260f1-6124-42bb-bb59-de0964252e8e)

I am not sure how to select `Yes` here. This is on a completely fresh install on a virtual box installation. It is very possible I am doing something silly, but in case not I'll leave this issue here. If I try again and running the Omakub script is successful I'll just delete this issue.

**Comment by therohitdas** [comment]
Press `enter`?

**Comment by rysllvn** [comment]
> Press `enter`?

Enter did not work on the VM or on a thinkpad. I can take a short video later when I try the script again.

**Comment by therohitdas** [comment]
Before running the installation script, set the `DEBIAN_FRONTEND="noninteractive"`
```bash
export DEBIAN_FRONTEND="noninteractive"
```
The last part of the script has YES/No prompts to install GNOME extensions, etc, I do not know if setting this will affect it. But it should bypass the YES/No prompt you are seeing. 


See - [StackOverflow Answer](https://unix.stackexchange.com/questions/106552/apt-get-install-without-debconf-prompt)

**Comment by dhh** [comment]
Yeah, this is a change from Microsoft's side. Working to get rid of it now by adding the signing keys manually before doing the install. We should not have this screen. Thanks for catching it @rysllvn!

**Comment by ifedan-ed** [comment]
I had this same issue, had to reboot...now stuck at "libvips has no installation candidate"

**Comment by rysllvn** [comment]
Thank you, adding the signing keys manually worked just fine. I'm writing this from a machine fresh from running the installer.

I added the MS repository and signing keys following their instructions [here ](https://code.visualstudio.com/docs/setup/linux) for installing  VS Code stopping short of the last step of actually installing VS Code. 

Specifically this:
```bash
sudo apt-get install wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
rm -f packages.microsoft.gpg

sudo apt install apt-transport-https
sudo apt update
```
And then I ran `wget -qO- https://omakub.org/install | bash`.

**Comment by dhh** [comment]
Fixed on dev. Doing a release now.

**Comment by ImaadCx** [comment]
I know this is a very late reply. But pressing spacebar works
