### ISSUE TITLE
Feature suggestion: Allow Podman as an alternate to Docker.

### ISSUE THREAD

**Issue by paul-hammant** [basecamp/omakub#27]
https://github.com/containers/podman

* Lean on system resources 
* Decent isolation
* Thriving dev community
* Talk I attended - https://www.slideshare.net/slideshow/power-up-with-podman-cloud-native-k8s-meetup/268620079

**Perhaps Distrobox too:**

https://github.com/89luca89/distrobox

* Will silently utilize Docker or Podman that's already installed.
* Deliberately shares home folder of (in this case Ubuntu) host with guest OS (which could be Redhat, etc)
* Luca needs to be cloned and the community is asking for more than one person can provide

**Comment by dhh** [comment]
Podman is great, but we're not going to do either/or with this. Docker is just installed as a baseline. Anyone is free to change that afterwards.
