### ISSUE TITLE
Auto-move-window extension

### ISSUE THREAD

**Issue by BP602** [basecamp/omakub#272]
https://extensions.gnome.org/extension/16/auto-move-windows/

This extension forces specific programs to open only in specific workspaces, it integrates really well with Omakub's setup. 

As suggested in the [docs](https://manual.omakub.org/1/read/8/navigation#workspaces)
And by the [shortcuts](https://github.com/basecamp/omakub/blob/30597f3aacc5fd339f44f72041ddf60fc1274f75/install/desktop/set-gnome-hotkeys.sh#L21)

> You should get in the habit of leaving the same application on the same workspace, so you can build up muscle memory for quick navigation. For example, here's how you could do it:
> 
> | # | Purpose | Program(s) | Hotkey |
> |---|--------------|------------------|------------|		
> |1 | Browsing | Chrome | Super + 1 | 
> |2 | Programming | Terminal | Super + 2 | 
> |3 | Communication | Signal + WhatsApp | Super + 3 | 
> |4 | Music | Spotify | Super + 4 | 
> |5 | Writing | Typora | Super + 5 | 
> |6 | Misc | Whatever | Super + 6 | 

Auto move windows strongly helps build that muscle memory and does all the setup that you would have to do manually at startup to place the right programs in the right workspaces.

Renaming workspaces to their purpose also helps 
![Screenshot from 2024-09-13 21-03-13](https://github.com/user-attachments/assets/85fbc378-545c-4519-a47a-f90377a6c803)

`gsettings set org.gnome.desktop.wm.preferences workspace-names  ["Browsing", "Programming", "Communication", "Music", "Writing", "Misc"]`

**Comment by dhh** [comment]
Yeah, I wouldn't love that. I do often open programs on different than default workspaces.
