### ISSUE TITLE
'Pano' extension shows as 'unsupported' under Ubuntu 24.04.1

### ISSUE THREAD

**Issue by shawnyeager** [basecamp/omakub#275]
Thanks for the great project.

I did a fresh install of Ubuntu 24.04.1 yesterday, and Pano shows as unsupported. While I was able to force the installation, it's not functional. Hopefully they'll sort it out. It's what I was looking forward to replace clipboard features from Raycast.

![2024-09-15_11-25](https://github.com/user-attachments/assets/7cc57b6c-04a9-477f-b5cd-0a932bc09cfd)

**Comment by dhh** [comment]
Yeah, we've removed pano from the default setup for now for this reason. When/if they get Gnome 46 compatibility, we'll add it back.

**Comment by shawnyeager** [comment]
Got it. I saw it in the manual, so went looking.
