### ISSUE TITLE
Adding a Telegram app

### ISSUE THREAD

**Issue by avelkov** [basecamp/omakub#276]
Hi Everyone,

I've added Telegram to my setup using the same method as WhatsApp and thought this would be a useful addition to Omakub - but I've also never contributed to an open source project before so not sure how to go about it correctly.

I simply created a Telegram.desktop file in .local/share/applications with the following code

`[Desktop Entry]
Version=1.0
Name=Telegram
Comment=Telegram Messenger
Exec=google-chrome --app="https://web.telegram.org" --name=Telegram --class=Telegram
Terminal=false
Type=Application
Icon=/home/[USER]/.local/share/omakub/applications/icons/Telegram.png
Categories=GTK;
MimeType=text/html;text/xml;application/xhtml_xml;
StartupNotify=true`

where [USER] is my username - I'm not sure how this would be applied to the install script to correctly go in the right folder.

Then I added the attached Icon to .local/share/omakub/applications/icons

How can I help more to get this into the code-base?

![Telegram](https://github.com/user-attachments/assets/3be9b41a-5afc-4146-8e4a-452022b2a727)

**Comment by florentdestremau** [comment]
FWIW there is a Telegram [native app for linux](https://desktop.telegram.org/) (and pretty great too)

**Comment by avelkov** [comment]
Ah, very useful indeed! Thanks.

Installing now, and undoing my manual addition.
