### ISSUE TITLE
Add pbcopy

### ISSUE THREAD

**Issue by so0k** [basecamp/omakub#281]
A simple trick to make transition from MacOS to Omakub even smoother

Not sure if it's already there or there's another (undocumented) way in omakub?

else something like this?

- add `xclip` to install/terminal/libraries.sh
- add `pbcopy` alias `"xclip -sel clip"` to `defaults/bash/aliases`

**Comment by so0k** [comment]
alternatively, point me to the docs (maybe it fits in https://manual.omakub.org/1/read/34/clipboard)

in case Zellij or alacritty have a special way to handle this

**Comment by horvay** [comment]
I needed to install xclip to copy an entire txt file from nvim. Otherwise gg"+yG doesn't work :(

**Comment by horvay** [comment]
I submitted https://github.com/basecamp/omakub/pull/282 in case it is wanted in the master repo 😄

**Comment by so0k** [comment]
for my case, can just alias `wl-copy` - just learned about it today
