### ISSUE TITLE
Build this thing on top of NixOS

### ISSUE THREAD

**Issue by adrian-gierakowski** [basecamp/omakub#285]
Doing it would maximise the probability of this project (and its offspring) thriving for the next 20 years. 

2 short videos for reference:
- https://youtu.be/5D3nUU1OVx8?si=OstxvH6uoUcm8y05
- https://youtu.be/X_jMqi-0SrM?si=yeWE-H4Nn3kqdlb2

I’d be honoured to donate 1.5 hour of my time a week to teach you about Nix\NixOS @dhh (for as long as necessary to make this happen).

**Comment by dhh** [comment]
Thanks for the offer, Adrian, but I'm very happy with this as an Ubuntu project. Feel free to be inspired by it and do a Nix version, though.
