### ISSUE TITLE
Issues installing golang 

### ISSUE THREAD

**Issue by cforte7** [basecamp/omakub#292]
Hello, I was having issues installing golang with omakub. 

I selected it both on the initial install and also from the Install menu in the `omakub` tui but it never actually installed. When doing it through the omakube Install menu, it instantly jumps to the success message without actually doing anything. 

I looked through the repo and saw this is just a wrapper around `mise use --global go@latest` and running that myself did install go successfully. 

This was done on a fresh Ubuntu 24.02 install. Let me know if you need any other info.

**Comment by James-N-M** [comment]
I'm seeing the same behavior when trying to install ruby on rails through the omakub install menu.

```
omakub
```

I checked out [select languages](https://github.com/basecamp/omakub/blob/34fb6b88567fbde5a753b72ae596a17babe97709/install/terminal/select-dev-language.sh#L13) and the command
```
mise use --global ruby@3.3
```
it didnt seem to be working but eventually did it just took a couple minutes.

**Comment by justinhhorner** [comment]
Hello! :wave: 

I just tested installing Go and it installed as expected. Make sure when you're selecting the language you want, even if it's just one, that you're using space bar to make the selection and then press Return/Enter.

If that's not the issue, report back and I'll troubleshoot this further to find out what's going on.

**Comment by cforte7** [comment]
I think that may have been my problem. I went and was able to install Ruby successfully and am going to assume that was also my problem on the initial install. Thanks for the insight, I am closing this out
