### ISSUE TITLE
Convert Gnome extension installs from gext to git clone

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#30]
We use 4 Gnome extensions, and we install them using gext. That causes the installer to pause for user input to confirm these installations. That's a pain. We should just clone the extensions straight into the Gnome directory and then turn them on. Then the installer can finish without any intervention from the user.

**Comment by iljo-dp** [comment]
I should just be done, currently testing it on a fresh vm
let me get the vm first

**Comment by jeremy** [comment]
The confirmation dialog is from Gnome itself. Looks like we can bypass confirmation by telling gext to use the filesystem backend instead of dbus: https://github.com/essembeh/gnome-extensions-cli/issues/13#issuecomment-1529160849

**Comment by dhh** [comment]
Oh, even better if we can just stick to gext and do a bypass like that.

**Comment by dhh** [comment]
Sadly the caution on that PR was right. Only 1 out of 4 gnome extensions used worked if installed like that. Will just live with it for now.
