### ISSUE TITLE
Installation hangs during Obsidian installation

### ISSUE THREAD

**Issue by damiensedgwick** [basecamp/omakub#303]
I am not entirely sure what causes the issue, but the first time of trying to go through the installation process, I thought I had accidentally pressed something and caused it to fail, however going through the process a 2nd time, it appears to be something that is happening without any input from the user.

During the installation of Obsidian, the terminal displays text characters similar to what you see if you press keys during an ongoing process (see pic) - It also hangs here for quite some time and it is unclear if it has crashed or if it is just processing something else.

It would be good to be able to show a status here or fix the issue seen in the image. I can provide laptop specs if needed but this was on a fresh install of 24.04

![Screenshot from 2024-10-11 10-49-38](https://github.com/user-attachments/assets/3fea8f28-e96f-4df9-a459-4f31d6c055d9)

**Comment by dhh** [comment]
Hmm, I can't replicate this. Just did a fresh setup and everything worked correctly. Wonder if there's some hardware issue or whatever with flatpak? Are you able to install Obsidian via flatpak without omakub?

**Comment by damiensedgwick** [comment]
> Hmm, I can't replicate this. Just did a fresh setup and everything worked correctly. Wonder if there's some hardware issue or whatever with flatpak? Are you able to install Obsidian via flatpak without omakub?

Apologies, after re-reading my comment, I realise I wasn't clear. Obsidian did finish installing successfully. The issue was the confusing text shown in the picture. I initially exited the process after seeing no progress and this text, but on the second attempt, I left it running, and everything installed fine (despite seeing the same text again).

The issue might be hardware related. I was installing on a ThinkPad T490 with an 8th gen Intel Core i5 processor, which I assume, should be fine?

As for a fix, since this appears to be an isolated incident, it might be best to close the issue as it will still be here for reference, in case others encounter the same problem and perhaps adding a warning that some installations can take a while would be helpful.

**Comment by cspolton** [comment]
I had the same issue. Having searched for potential fixes, after a lengthy pause at this point (~10 minutes I'm guessing), I returned to my new Framework13 to find it had actually progressed a little. A warning would be useful.

**Comment by liambeeton** [comment]
I also had this issue today and after a very long wait I got a message that said [Pinta from James Carroll](https://snapcraft.io/install/pinta-james-carroll/debian) installed and then got the prompt to elevate permissions and enter my password. Installation continued after that.

**Comment by prajulaaditya007** [comment]
I was trying Fedora for sometime, But now, I so used to this, I booted Ubuntu 24.10 and got in this issue, I reinstalled it, got the same issue again. Booted into Ubuntu 24.04.1 now, still got the same issue.
I am just waiting now, it's surely taking a long time.

**Comment by dhh** [comment]
Just did a clean 24.10 install. Obsidian definitely is one of the longer installs, and there's not a lot of feedback while it's running. But on my Framework laptop it took about a minute. Maybe we can print a warning on the obsidian install that it might take several minutes.

**Comment by bpiroman** [comment]
The same thing happened to me, i'm using a Framework 13 (13th gen intel core) laptop with a fresh Ubuntu 24.04 install. I think it was hanging for around 20mins. Good thing I found this issue!

**Comment by jaykilleen** [comment]
I just did a fresh install on a new Lenovo Thinkbook 16 G7 IML. It hung at the same point with Obsidian for around 10 mins (enough for me to want to Google) and then just kept going as usual with no more issues. Thanks for making this @dhh. It is 🔥

**Comment by dhh** [comment]
Yeah, we really need to add a warning before the installer that it might take a very long time on slower hardware. Crazy that the flatpak installation is that damn slow. On my Framework, it also does take a while. But like 30 seconds or so. Maybe it's actually also a bandwidth issue? That is it has download half the internet?
