### ISSUE TITLE
Ubuntu 24.10 support?

### ISSUE THREAD

**Issue by KimTholstorf** [basecamp/omakub#320]
Ubuntu 24.10 is out. Do you plan to have Omakub support 24.10 ?

**Comment by Kasui92** [comment]
Based on what was said [here](https://github.com/basecamp/omakub/issues/302#issuecomment-2407978167), Omakub only follows the current LTS version for now.

**Comment by dhh** [comment]
Happy to make it compatible if someone wants to do the work and it doesn't have negative effects for the LTS version.

**Comment by skyscooby** [comment]
I tried on a 24.10 fresh install last week and I didn't notice anything specifically broken.. probably just needs a little QA from an 'expert' user to confirm but it looked all pretty like the screenshots after install :)

**Comment by dhh** [comment]
Seems like everything is working as it should be.
