### ISSUE TITLE
Neovim navigation shortcuts won't work with Zellij

### ISSUE THREAD

**Issue by akitaonrails** [basecamp/omakub#326]
When I have neo-tree or a split panel within Neovim, I should be able to navigate using Ctrl + (h j k l), but because Zellij use the same Ctrl modifier, that won't work.

This is a known misbehavior from Zellij and one of the possible solutions is this: 

https://shoukoo.github.io/blog/zellij-love-neovim/

It's adding a "tmux" mode. That way we recover Neovim's shortcuts within Zellij while in "normal" mode, but we can just Ctrl modifiers, while in "tmux mode".

Here is the [full source](https://github.com/shoukoo/dotfiles/blob/master/zellij.kdl) for a better zellij.kdl

**Comment by dhh** [comment]
Zellij resolved this in 0.4: https://zellij.dev/news/colliding-keybinds-plugin-manager/
