### ISSUE TITLE
Neovim missing a plugin after install

### ISSUE THREAD

**Issue by florentdestremau** [basecamp/omakub#33]
Fresh install on a Framework 13 Intel.
When launching neovim I seem to be missing a lazy plugin. Tried reinstalling the `app-neovim.sh` but it did not fix it.

![image](https://github.com/basecamp/omakub/assets/2852204/0ce6979f-d5ab-47d7-8775-bbcda90409fc)

**Comment by florentdestremau** [comment]
disclosure: I updated a bit on my fork, but it's up-to-date and really just disabling some installs I don't need + adding a couple of mines. To my knowledge, this should not influence the rest.

https://github.com/basecamp/omakub/compare/master...florentdestremau:omakub:master?expand=1

**Comment by dhh** [comment]
can you do "n --version"?

**Comment by florentdestremau** [comment]
```
 n --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by florentdestremau** [comment]
Reinstalled the script after having deleted the nvim config folder, no errors now. 🤷
