### ISSUE TITLE
Symbols (folders and arrow) not appearing on terminal/Alacritty

### ISSUE THREAD

**Issue by achvaicer** [basecamp/omakub#335]
Just installed omakub on Ubuntu 24.04, and something is missing in the fonts or icons, since is not appearing any folder and arrow symbols.

![image](https://github.com/user-attachments/assets/cba8b185-4f72-44a4-bec6-e9ddc0ed3669)
![image](https://github.com/user-attachments/assets/a646567b-f277-4fb6-9b9a-7714c862a674)

**Comment by dhh** [comment]
Looks like you're missing the nerd fonts. They're installed when you do a clean installation on a new Ubuntu. Sounds like maybe you installed on an existing setup?

You can try to switch font using the Omakub command and see if that sorts it.

**Comment by achvaicer** [comment]
It was a fresh installed Ubuntu, and I had already switched to other fonts. Didn't worked.
After download a font from nerdfonts.com and unzipped, it worked.

**Comment by dhh** [comment]
Strange. Just did a clean install and couldn't replicate. Maybe the nerd font installation somehow failed due to network issues on their end at the time.
