### ISSUE TITLE
Omakub available for arch Linux.

### ISSUE THREAD

**Issue by anthobio23** [basecamp/omakub#35]
Hi, I can use omakub in arch Linux?

**Comment by iljo-dp** [comment]
nope, this is an ubuntu setup script, sorry. There are also no plans to support arch at this moment in time if I understand dhh correctly

**Comment by dhh** [comment]
Correct. Arch is for the uber nerds anyway. Aren't they all also running i3? That wouldn't work with the many Gnome tweaks in this box.

**Comment by markhilkert** [comment]
Just in case anyone shows up here looking for an arch version, it's a thing now: https://omarchy.org/

**Comment by gerrywastaken** [comment]
For the historians: https://x.com/dhh/status/1961663052312354826
