### ISSUE TITLE
Replace Snap with Flatpak?

### ISSUE THREAD

**Issue by osbre** [basecamp/omakub#37]
Hi. How'd you feel about getting rid of Snap in favour of [Flatpak](https://flatpak.org/)? I can send a PR.

I think the majority of experienced Linux users would agree that Snap is one of those things that makes Ubuntu worse in comparison to other distros.

Flatpak also has a package for the gnome store ("Ubuntu Software Center"), so there would be compromises in terms of user experience, IMO.

**Comment by iljo-dp** [comment]
the plan is to get rid of snaps that is true, currently I don't remember any snaps being installed if my request to add arm64 support comes in

**Comment by iljo-dp** [comment]
but we could 100% use flatpaks for the apps that don't support native packages like chrome or others

**Comment by dhh** [comment]
There's only one app left in Omakub still using snap and that's pinta. Would prefer to install that directly without either, but if that's not possible, I'm not against exploring using flatpak instead.

**Comment by iljo-dp** [comment]
> There's only one app left in Omakub still using snap and that's pinta. Would prefer to install that directly without either, but if that's not possible, I'm not against exploring using flatpak instead.

Just realised I made a mistake in my arm version, quick question would you rather have a ppa or a snap?

**Comment by iljo-dp** [comment]
> There's only one app left in Omakub still using snap and that's pinta. Would prefer to install that directly without either, but if that's not possible, I'm not against exploring using flatpak instead.

what is the opinion on flatpaks for things like chrome for arm64? since google doesn't have an arm version

**Comment by dhh** [comment]
Ppa over snap for sure. I could live with flatpak when there's no other choice.
