### ISSUE TITLE
Dotfile manager discussion

### ISSUE THREAD

**Issue by nahue** [basecamp/omakub#41]
I have been thinking about setting up a dotfile manager like chezmoi, yadm or similar.

Maybe omakub can provide a opinionated way of managing dotfiles so its easier to mantain configs across multiple machines?

**Comment by dhh** [comment]
I like Stow, but I'm also not sure we need something out of the box, since the box is already preconfigured. I don't actually use anything at the moment. Will keep in mind, though, thanks!
