### ISSUE TITLE
nodenv error after installing.

### ISSUE THREAD

**Issue by Mtendekuyokwa19** [basecamp/omakub#44]
![Screenshot from 2024-06-08 09-27-30](https://github.com/basecamp/omakub/assets/103486923/c8c187f8-575a-4950-b54d-8c7355d6ea7c)

Been getting this error. I want to remove it and my terminal should go back to default settings

**Comment by dhh** [comment]
Run `omakub update`. Then start terminal again. Should prompt to install mise.
