### ISSUE TITLE
Document weird caps locks behaviour if it was previously assigned as CTRL

### ISSUE THREAD

**Issue by domluna** [basecamp/omakub#48]
This is only an issue if you previously mapped caps lock to ctrl. If that is the case then the ctrl behaviour conflicts with the emoji behaviour set in https://github.com/basecamp/omakub/blob/master/install/set-emojis.sh.

My solution was to just reset whatever was done in that file.

It's unclear to me where or even whether the maintainers would want to document this.

I'm opening this issue in case someone else has the same problem on install and is driven mad at 3am by their ctrl key suddenly acting in an incredibly bizzare way.

**Comment by dhh** [comment]
Definitely need to document this, yes. Will be part of the manual!
