### ISSUE TITLE
Consider adding support for other distributions

### ISSUE THREAD

**Issue by con5ole** [basecamp/omakub#49]
Seems to me that support for other distros could be added to Omakub simply by adding distro-specific "install"-subfolders and having the main setup script do a `cat /etc/*-release` to determine which subfolder to run the install-scripts from. 

There would be a lot of duplication but it would be easy to understand.

**Comment by iljo-dp** [comment]
Please read #35 omakub won't be supporting anything else then ubuntu

**Comment by dhh** [comment]
Yeah, I could see accommodating other Ubuntu-derived distros that ship with both Gnome and apt, like Pop!, but that's probably as far as we can stretch here and still have a unified experience. I've opened a separate ticket for Pop! compatibility.

**Comment by con5ole** [comment]
> Yeah, I could see accommodating other Ubuntu-derived distros that ship with both Gnome and apt, like Pop!, but that's probably as far as we can stretch here and still have a unified experience. I've opened a separate ticket for Pop! compatibility.

I fully agree that the experience should not be compromised.

I did some work yesterday getting Omakub to work identically on Debian 12 and Ubuntu, but couldn't get to 100%. The worst was having to drop Ruby to 3.1, so the experience is not identical. 

I might continue tinkering with it since it seems to me that generally speaking having Omakub be based on a distro as far "upstream" as possible could be a good idea. I suspect that it will be easier to make a set of scripts that work fine on Debian also work on any "Debian and below"-based distros, including Ubuntu. 

Happy to hear you considering another distro at all. Thanks a lot for sharing both the work and the enthusiasm!
