### ISSUE TITLE
Default chrome theme has weird mix of rounded and square corners

### ISSUE THREAD

**Issue by winstonpurnomo** [basecamp/omakub#54]
![Screenshot from 2024-06-09 10-14-27](https://github.com/basecamp/omakub/assets/54757320/84d1df93-6f1f-4145-8295-9cf30764a546)

See the above screenshot for reference. Notice how the top ones have rounded corners but the bottom ones are squared off.  I understand this is the default behavior in many Linux builds but ot'd be nice to fix

**Comment by dhh** [comment]
I think that's just Chrome as it is. But we're exploring using Chrome themes to match colors. I'd be happy to entertain something else for the look. Please open a PR if you find something worth considering.
