### ISSUE TITLE
Consider converting this project to an ansible playbook

### ISSUE THREAD

**Issue by TerrorSquad** [basecamp/omakub#60]
This project is used to install and configure software after a fresh Ubuntu installation, and as such is a perfect project for using Ansible. Ansible allows you to declaratively write what you want to be configured and installed in simple yaml files using various inbuilt Ansible modules. This approach is better because Ansible modules allow for better scalability, idempotency and error handling.

Consider taking a look at this repo for inspiration https://github.com/TerrorSquad/ansible-post-installation

It is also opinionated and it's meant to be used right after Ubuntu installation. It will install a bunch of software for development, terminals such as Alacritty and Terminator (with custom config), nvim, docker, go, cargo, node (via volta package manager). There is also Zsh with a very fast and robust config. Packages are mostly installed from official Ubuntu repositories, but some of them are installed via Homebrew as it provides newer versions to certain packages.

**Comment by dhh** [comment]
Thanks for the suggestion, but happy with bash for now. Don't want to mix Homebrew into things.

**Comment by TerrorSquad** [comment]
You're welcome.
Bash is fine, it's just that it can get tedious for more complex things. Also, you don't have to use Homebrew if you don't want to ;)

**Comment by dhh** [comment]
That's exactly why I want to use bash! As a constraint that pushes back on complexity. I was tempted to use Ruby early on in the project, but found that embracing bash held the line on complexity better.
