### ISSUE TITLE
Warn on setup that Omakub is for a FRESH 24.04 setup

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#63]
I've seen at least one person mention that Omakub screwed something up on their main machine. That's no good. Need to make clear when the installer runs that this is for a fresh system, you should have a backup, and so far we've only verified compatibility with 24.04.

**Comment by 2KAbhishek** [comment]
I'll take this, 

we can check if any of the config dirs already exists and then inform the user that installation should be ran on a fresh ubuntu setup along with showing a prompt if they still want to go ahead.

**Comment by dhh** [comment]
I've added a basic notice to the installer for now. Can consider upgrading that later.
