### ISSUE TITLE
Make neovim background transparent

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#64]
Our default Alacritty configuration has an ever-so-slight translucency that's really nice without harming readability. It's set to 97% in the config. But neovim isn't translucent in this setup. We need to change something in the theme options, I believe, for it to use the terminal translucency. Let's find and add that.

**Comment by iljo-dp** [comment]
I have a very very non elegant (half) working solution
if this is put in the lazy.lua at the bottom for example it will work

vim.cmd([[
  augroup TransparentBackground
    autocmd!
    autocmd ColorScheme * highlight Normal ctermbg=none guibg=none
    autocmd ColorScheme * highlight NonText ctermbg=none guibg=none
  augroup END
]])
vim.cmd("colorscheme tokyonight")

This works, just tested it, but the biggest problem here is that the theme here is hardcoded, fixing this rn

**Comment by 2KAbhishek** [comment]
@dhh can this be closed now? since #71 is merged in 🤔

**Comment by dhh** [comment]
Had to revert #71. Wasn't working on my end. So let's keep open until resolved.

**Comment by 2KAbhishek** [comment]
I'll take a look and update the PR

**Comment by anselal** [comment]
require("tokyonight").setup({
      transparent = true,
      styles = {
        sidebars = "transparent",
        floats = "transparent",
      },
    })


replace `tokyonight` is your theme

**Comment by miniMinn24** [comment]
> require("tokyonight").setup({ transparent = true, styles = { sidebars = "transparent", floats = "transparent", }, })
> 
> replace `tokyonight` is your theme

This actually works!
