### ISSUE TITLE
Sync theme with Chrome theme extension

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#65]
Chrome has some very nice theme extensions that really match the look we're going for. It would be great if we could fix or build a matching theme for chrome for our 7 default setups. Here's the Nord theme, for example: https://chromewebstore.google.com/detail/nord-theme/dhlnjfhjjbminbjbegeiijdakdkamjoi?utm_source=ext_app_menu

Chrome stores its preferencs in ~/.config/google-chrome/Default/Preferences. It's a json file. I think we could probably use jq to substitute in the theme we need.

**Comment by dhh** [comment]
It's possible to change the color tones with: `sed -i 's/"user_color":-[0-9]\+}/"user_color":-27650}/g' ~/.config/google-chrome/Default/Preferences`, but it requires that Chrome has been quit first, or it'll just get overwritten. So need a prompt to ask to quit Chrome in order to match colors.

**Comment by jkjarvis** [comment]
Let me check this.

**Comment by dhh** [comment]
Great! Bonus points if we can figure out how to use the wallpaper as well as in the theme.

**Comment by jkjarvis** [comment]
Wow, in my preferences file, there is no user_color key by default. Did you tweak or applied anything in your chrome?

**Comment by dhh** [comment]
I tweaked it. You set it from the lower right pen on a blank screen. This is a color match for Everforest, for example: `"theme":{"color_variant":2,"follows_system_colors":false,"user_color":-7829368}`.

**Comment by MislavPukljak** [comment]
Also in preferences file I added this code to change background, also chrome needs to be closed while modifying this file, but it works. Start position was default theme in chrome.
`"ntp":{"custom_background_dict":{"background_url":"https://github.com/basecamp/omakub/blob/master/backgrounds/fog_forest_2.jpg?raw=true"},"custom_background_inspiration":false,"custom_background_local_to_device":false,"num_personal_suggestions":9}`

**Comment by dhh** [comment]
Awesome. So what I'm thinking is that when you pick your theme, we'll ask via gum whether you also want to update chrome, and warn that this requires restarting chrome. If user agrees, then close chrome, change the config, re-open chrome.

**Comment by dhh** [comment]
Should use the existing backgrounds we already have and then pick the best matching color to go with that.

**Comment by dhh** [comment]
We don't need to use any of the actual theme extensions. The user colors are good enough.

**Comment by jkjarvis** [comment]
I feel dumb but I followed the following:
1. I set a theme on chrome and in my preferences file got the "user_color" flag for color_variant:1
2. Then I exited the chrome and ran the sed command and verified the value is changed
3. Opened chrome again but it reversed the value to previous one.
4. I also tried with vim and saved the custom value but upon opening chrome, it again reversed the value.

**Comment by dhh** [comment]
Chrome has to be closed when you make the change. It overwrites Preferences on exit. And it doesn't load live.

**Comment by jkjarvis** [comment]
Got it finally.
I noticed few things:
1. When i applied a theme, it created another theme key value where some "system_theme_id" was written
2. I changed the color in color key and also added the same fields in the other theme key value anf removed the system_id/ theme_id already mentioned.
3. Maybe try to earch using "color" in your configs

While doing this, 1 case I saw, what if user had sync settings on, will it override and apply local settings to other devices or will it override this system with previous ones.
Do you have sync settings on ? Is it changing the theme on other devices keeping it same on OMAKUB

**Comment by jkjarvis** [comment]
1. "theme":{"color_variant":1,"user_color":-336013}  - this which i was editing and you guys also did

2. "theme":{"id":"user_color_theme_id","system_theme":0} - this i found and added the above two variables with custom values and then it worked

**Comment by MislavPukljak** [comment]
Those key value is added by changing theme and I do not see reason to touch it, because it do not affect anything.
This config I posted here is just example how can it be done, it is different for every theme.

Good point for Sync question, I will check that also

**Comment by jkjarvis** [comment]
I am also working on this, do you want a common branch ? Or maybe divide features? I can do color configs and will try the popup. Do you wanna do the image part ?

**Comment by MislavPukljak** [comment]
I already did a few things, write jq command for changing theme and
picture, also tried to change chrome theme through umakub theme selector,
also added pop up.

**Comment by MislavPukljak** [comment]
I already did a few things, write jq command for changing theme and picture, also tried to change chrome theme through umakub theme selector, also added pop up.

The ona thing would be very helpfull, and that is color config for each theme.

**Comment by jkjarvis** [comment]
let me find those, are these in rgb? I downloaded the tokyo night from webstore but it doesn't have a single value but in array (maybe rgb) 
https://chromewebstore.google.com/detail/tokyonight/enpfonmmpgoinjpglildebkaphbhndek

**Comment by jkjarvis** [comment]
got it, gpt says its ARGB

**Comment by MislavPukljak** [comment]
Not really, what did I found out the color is changing by changing this number ("user_color":-7829368) and by changing color_variant from 1 to 4.

It should be ARGB but I didn't spend much time about color choosing.

**Comment by jkjarvis** [comment]
yeah, maybe for initial base versions we can keep the user_color toggles , if someone already has a third party theme, it might be difficult to override. btw im only changing color and not the color_variant value, it is working

**Comment by MislavPukljak** [comment]
If you will have some problem with finding color, try to change color_variant.
As I am aware of values: 1 and 3 are slightly brighter colors.
Hope it helps
