### ISSUE TITLE
Better description of the software included

### ISSUE THREAD

**Issue by enriquemorenotent** [basecamp/omakub#7]
It would be nice to have a list with all the installed programs included. Right now you have to read through the README that, while more comprehensive, it is harder to browse through. Something simple like

* Whatsapp
* VSCode
* Alacritty
* ...

Maybe even with a link to their respective home sites.

**Comment by jeffreyguenther** [comment]
I bet if you opened a PR, he would merge it!

**Comment by enriquemorenotent** [comment]
Yeah, but sadly I have yet to try Omakub :stuck_out_tongue: 

My Ubuntu system is way too old and tweaked. I fear that it could do. I would try it right away if I had a fresh one, that's for sure.

**Comment by jeffreyguenther** [comment]
I don't think you need to try Omakub to add to the docs. Jus say'n 😄 A little source diving and you'll have your list.

**Comment by enriquemorenotent** [comment]
Oh, I would never dare to document something I have never tried! :no_good_man:

**Comment by enriquemorenotent** [comment]
Lovely, thanks
