### ISSUE TITLE
Add default setup for PHP

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#73]
Omakub should be for developers from a large number of communities, and it should work out of the box for them. What's needed for an out-of-the-box experience for PHP, say, someone developing Laravel?

**Comment by florentdestremau** [comment]
I have a very simple setup on my fork, works like a charm since my install 3 days ago: https://github.com/florentdestremau/omakub/blob/master/install/php.sh

I'm a Symfony developper so I don't have a good idea of where Laravel might need some tweaks, and it includes extensions that are specific for my project (and some choices such as db drivers).

It also includes the Symfony console so that's framework-specific too.

**Comment by blankRSD** [comment]
For Laravel, one of the easiest way to setup a complete dev environment is to use [Sail](https://laravel.com/docs/11.x/installation#choosing-your-sail-services) which packages all the docker dependencies for each project. 

Otherwise, LEMP stack is still one of the most used stack.

**Comment by TerrorSquad** [comment]
PHP installed via APT should be enough for execution of some random scripts when you need an PHP interpreter.

But for actual projects, having a complete dedicated environment is a must. DDEV is the de-facto standard for this. You install it once globally and then use it to create an environment for each project you're working on.
https://ddev.readthedocs.io/en/latest/users/quickstart/#laravel

I've been using it for a few projects (php7.4, 8.2  and 8.3), it's great. You can customize it with custom scripts and Dockerfiles.

Another great environment I used a lot (~4 years) is https://github.com/markshust/docker-magento - this one is specific to Magento 2 though and is a better choice for it than DDEV.

**Comment by jasonmccallister** [comment]
DDEV might be overkill, especially for Ubuntu - I have always defaulted to using this PPA https://launchpad.net/~ondrej/+archive/ubuntu/php.

Since Ruby and Go are installed on the system with mise, might make sense to also install PHP on the system?

**Comment by jasonmccallister** [comment]
Good point @nickchomey, I still think its overkill for installing PHP on the system

**Comment by csfh** [comment]
I think it's worth considering using Valet instead of Sail. Or at least give both options.

I started out with Sail myself but after a while I find Valet and Herd to be better for local development for Laravel.

**Comment by osbre** [comment]
IMO, the best way to get PHP is via `ppa:ondrej/php`. It's becoming a standard practice on the server as everyone trusts this repo and it's good.

**Comment by csfh** [comment]
Maybe we start simple. ondrej + composer. Which extensions should be included?

**Comment by roelandmoors** [comment]
> Maybe we start simple. ondrej + composer. Which extensions should be included?

I agree, PR #87 is installing that.

**Comment by florentdestremau** [comment]
I added very basic ones with the 3 main db drivers. Doesn't hurt to put too much extensions but I guess it could scare some people away ? We're back to the debat on having all defaults vs "bundles" of dev environments. IMO I would keep the minimal, most projects have their own README::Install anyways, and most frameworks for beginners have their own self check as well.
