### ISSUE TITLE
Neovim stable PPA is incompatible with Lazyvim

### ISSUE THREAD

**Issue by andreimaxim** [basecamp/omakub#86]
The neovim install script adds the neovim stable PPA, but the [latest release in the PPA is 0.7.2](https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu/pool/main/n/neovim/), which is incompatible with LazyVim ([minimum version 0.9.0](https://github.com/LazyVim/LazyVim?tab=readme-ov-file#%EF%B8%8F-requirements)). 

Ubuntu 24.04 has [a newer neovim package (0.9.5)](https://packages.ubuntu.com/noble/neovim) and `apt install neovim` will install the newer version, so the PPA is unnecessary.

**Comment by iljo-dp** [comment]
perhaps read everything in #6 , where there was an extensive talk about how to migrate neovim away from ppa's. in the end it didn't get resolved, perhaps you can weigh in there? Imo i'd still rather go with a prebuilt binary but that is just an opinion

**Comment by andreimaxim** [comment]
@iljo-dp that's a different discussion.

What I'm saying is that 

```
sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo apt update
sudo apt install -y neovim
```

can be simply replaced with:

```
sudo apt install -y neovim
```

as the `neovim-ppa/stable` has an older version of neovim than the Ubuntu 24.04 official repositories, so the version in the PPA is never used.
