### ISSUE TITLE
Omakub working with other languages

### ISSUE THREAD

**Issue by 43hershel** [basecamp/omakub#91]
A fresh Ubuntu install in Spanish instead of English changes the names of the directories (e.g. Downloads - > Descargas) so the apps that get downloaded from .deb packages don't recognize Downloads directories in other languages. Therefore they don't get installed.

**Comment by rmacklin** [comment]
Have you seen https://github.com/basecamp/omakub/commit/ec7655e75e6a8806c49b16c624c56ea75ff1eb51 ?

**Comment by 43hershel** [comment]
I pointed it out in the morning inside campfire and it seems it has already been solved. Thank you
