### ISSUE TITLE
Create a Gnome extension for quick theme switching

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#94]
Would be great to have a gnome extension for quickly switching between themes. Maybe fonts too. Just a dropdown menu from a panel icon to trigger the omakub script for the changes.

**Comment by csfh** [comment]
How would this work? I'd like to work on this as well.

Can you point me in the right direction?

**Comment by iljo-dp** [comment]
ohh so just making a custom gnome extension, sounds interesting, perhaps open a new repo for that? I'd love to work on that, but that is perhaps better suited for a different repo?

**Comment by iljo-dp** [comment]
I have a bit of knowledge on that subject and I'd love to help, but imo a new repo would be a better fit?

**Comment by dhh** [comment]
On second thoughts, I don't think we need a gnome extension. I'm working on adding a Omakub.desktop file that can be launched from ulauncher and that'll start a tailored terminal session with the omakub command. Think that's the better way to go anyway.
