### ISSUE TITLE
Common aliases

### ISSUE THREAD

**Issue by csfh** [basecamp/omakub#95]
I think including a couple more commonly used aliases would be great.

For example:

- gco for git checkout
- lzd for lazydocker

Please comment with other suggestions.

**Comment by florentdestremau** [comment]
This make me think about #82 , zsh with oh-my-zsh has a large and [nice set of git aliases](https://kapeli.com/cheat_sheets/Oh-My-Zsh_Git.docset/Contents/Resources/Documents/index).

**Comment by dhh** [comment]
We have a bunch of aliases for things you need to type all the time here: https://github.com/basecamp/omakub/blob/master/defaults/bash/aliases

I don't want to go overboard here, though. But I'd go for lzd and lzg for lazydocker/git.
