### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by Paulie420** [basecamp/omakub#96]
I know this isn't the space for this, but I just wanted to say w0w - congrats, and thanks for OMAKUB! I've hopped back and forth from TWMs to Plasma 6 to.... all of the above and am very impressed with your implementation in OMAKUB...

The keybinds are very simply to learn and understand, much less overwhelming than a wild and crazy Hyprland full implementation - you inspire me to create tools for Nix, that could be installed on a wider variety of hardware/software or for other flavors of Linux... I'm wowwed by the simplicity and beauty of OMAKUB - I'll be creating a Youtube video covering it... great work, DHH.

Maybe I need to take another look at ROR!

**Comment by dhh** [comment]
Thanks @Paulie420! ✌️
